DEP_NAME = {
    'MSD': 'Marketing and Sales Department',
    'FD': 'Finance Department',
    'POD': 'Production and Operations Department',
    'CSD': 'Customer Service Department',
    'PD': 'Purchasing Department',
    'ITD': 'IT Department',
    'HRD': 'Human Resources Department',
    'MD': 'Mine Department'
}

DEPS = {
    "MSD": {
        "MD": "Marketing Director",
        "MMG": "Marketing Manager",
        "MCO": "Marketing Coordinator",
        "MAN": "Marketing Analyst",
        "MS": "Marketing Specialist",
        "SD": "Sales Director",
        "SMG": "Sales Manager",
        "SRE": "Sales Representative",
        "SS": "Sales Specialist",
        "SC": "Sales Consultant"
    },
    "FD": {
        "FMG": "Finance Manager",
        "FAN": "Financial Analyst",
        "FCO": "Financial Controller",
        "FCL": "Finance Clerk",
        "FAD": "Financial Advisor",
        "FM": "Finance Manager",
        "ACC": "Accountant",
        "FA": "Financial Analyst",
        "AUD": "Auditor",
        "CON": "Controller",
        "TRE": "Treasurer",
        "BA": "Budget Analyst",
        "TS": "Tax Specialist",
        "PC": "Payroll Clerk"
    },
    "POD": {
        "OMG": "Operations Manager",
        "PMG": "Production Manager",
        "OAN": "Operations Analyst",
        "PPL": "Production Planner",
        "OM": "Operations Manager",
        "PS": "Production Supervisor",
        "WHS": "Warehouse Specialist",
        "IM": "Inventory Manager",
        "PM": "Plant Manager",
        "PW": "Production Worker",
        "QCS": "Quality Control Specialist",
        "PP": "Production Planner",
        "LC": "Logistics Coordinator",
        "OA": "Operations Analyst",
        "QAM": "Quality Assurance Manager"
    },
    "CSD": {
        "CSM": "Customer Service Manager",
        "CSR": "Customer Service Representative",
        "CSS": "Customer Support Specialist",
        "CEM": "Customer Experience Manager",
        "CSR": "Customer Service Representative",
        "HDS": "Help Desk Specialist",
        "CSM": "Customer Service Manager",
        "CCA": "Call Center Agent",
        "TSS": "Technical Support Specialist",
        "AM": "Account Manager",
        "CRM": "Client Relations Manager",
        "SDA": "Service Desk Analyst",
        "CSE": "Customer Support Engineer",
        "CEM": "Customer Experience Manager"
    },
    "PD": {
        "PMG": "Purchasing Manager",
        "PAG": "Purchasing Agent",
        "PCS": "Procurement Specialist",
        "PCL": "Purchasing Clerk",
        "PAN": "Procurement Analyst",
        "PM": "Purchasing Manager",
        "BUY": "Buyer",
        "PS": "Procurement Specialist",
        "PC": "Purchasing Clerk",
        "SCA": "Supply Chain Analyst",
        "VM": "Vendor Manager",
        "PRM": "Procurement Manager",
        "PCO": "Purchasing Coordinator",
        "ICS": "Inventory Control Specialist",
        "PA": "Purchasing Agent"
    },
    "ITD": {
        "ITM": "IT Manager",
        "ITT": "IT Technician",
        "NEN": "Network Engineer",
        "SDE": "Software Developer",
        "ISS": "IT Support Specialist",
        "ITM": "IT Manager",
        "SA": "Systems Administrator",
        "NE": "Network Engineer",
        "DBA": "Database Administrator",
        "ISS": "IT Support Specialist",
        "SD": "Software Developer",
        "ITA": "IT Analyst",
        "IPM": "IT Project Manager",
        "SEC": "Security Analyst",
        "WD": "Web Developer"
    },
    "HRD": {
        "HRS": "Human Resources Specialist",
        "HRM": "Human Resources Manager",
        "RS": "Recruitment Specialist",
        "TC": "Training Coordinator",
        "BA": "Benefits Administrator",
        "HRA": "HR Analyst",
        "ERM": "Employee Relations Manager",
        "HRC": "HR Consultant",
        "PS": "Payroll Specialist",
        "HRA": "HR Assistant"
    },
    "MD": {
        "MBW": "Mine Blaster Worker",
        "UM": "Underground Miner",
        "HEO": "Heavy Equipment Operator",
        "DR": "Driller",
        "EL": "Electrician",
        "MTP": "Material Planner",
        "HSS": "Health and Safety Specialist",
        "MNM": "Mine Manager",
        "CH": "Chemist",
        "GE": "Geological Engineer"
    }
}
